== Déployer un service depuis le catalogue

OpenShift fournit un catalogue contenant des templates de tout type d'applications, base de données etc ... 
On peut égallement créer ses propres templates, il s'agit d'une resource OpenShift au format `yaml`. 


L'application qu'on va déployer est le service qui fournit la liste des incidents, pour l'instant on va uniquement le déployer mais lors du challenge 5 on le consommera avec notre première application.

=== Déployer le template et l'instancier [*Challenge 4.1*]

Voici le template que vous allez utiliser : https://gist.github.com/sebastienblanc/1ddaabb0fd87aeba5b1fb9241aa0c653

==== Preuves à fournir 

* [*Challenge 4.1.1*] Screenshot qui montre le template dans le catalogue
* [*Challenge 4.1.2*] Screenshot qui montre la création d'une instance du catalogue
* [*Challenge 4.1.3*] URL vers le nouvel service déployé

=== Customiser le template [*Challenge 4.2*]

Comme vous pouvez le voir, la resource `Secret` a une valeur "en dur" dans le template.
Le but de ce challenge est de rendre cette valeur paramètrable.

Vous pouvez trouver de la documentation sur les templates ici : https://docs.openshift.com/container-platform/4.8/openshift_images/using-templates.html#templates-writing_using-templates

Le service `antennas-incidents` dispose d'une interface swagger , vous pouvez y accèder avec votre route suivis de `/q/swagger-ui` , vous pouvez ainsi tester `rest/incidents` qui nécessite la valeur du secret. 


==== Preuves à fournir 

* [*Challenge 4.2.1*] Gist ou screenshot du template modifié
* [*Challenge 4.2.2*] Screenshot de la création d'une instance de template avec le champs `APIKEY`
* [*Challenge 4.2.3*] Screenshot de swagger-ui avec l'appel à `rest/incidents` qui retourne la liste des incidents





