== Consommation d'un service

Maintenant que nous avons `antennas-incident` de deployé nous alors devoir modifier notre première application, `antennas-front`,  afin qu'elle puisse récupèrer la liste des incidents du service distant.

Il va falloir un petit peu coder :) 

Voici un guide sur comment utiliser le `rest-client` de Quarkus : https://quarkus.io/guides/rest-client

=== Consommer le service distant avec APIKEY "en dur"  [*Challenge 5.1*]  __Beginner__

Le `antennas-incident` expose un point REST `/rest/incidents?APIKEY=mysecret` , pensez bien à utiliser la valeur correcte.
Vous pouvez accèder au sein du cluster au service avec `http://antennas-incident/` , pour ceci pensez bien à rajouter une variable d'environnemnt avec cette clef :
`ORG_SEBI_INCIDENT_INCIDENTSERVICE_MP_REST_URL`

==== Preuves à fournir 

* [*Challenge 5.1.1*] URL de l'application front qui montre qu'elle consomme le service distant.

=== Consommer le service distant en utilisant l'APIKEY fournit par le Secret [*Challenge 5.2*] __Advanced__

Au lieu de faire votre appel au service distant en passant l'APIKEY modifié l'application et les resources k8s afin de "coupler" le secret à votre application. 

==== Preuves à fournir 

* [*Challenge 5.2.1*] Screenshot ou gist qui montre le `Deployment` est "couplé" au secret.
* [*Challenge 5.2.2*] URL de l'application front qui montre qu'elle consomme le service distant.

