== Service Mesh

Pour ce dernier challenge nous allons installer un Service Mesh sur notre cluster. 


=== Installation de l'Operator Service Mesh

Ce n'est pas un mais quatre Operators que vous allez devoir installer, suivez bien les instructions sur ces pages : 

* https://docs.openshift.com/container-platform/4.8/service_mesh/v2x/installing-ossm.html
* https://docs.openshift.com/container-platform/4.8/service_mesh/v2x/ossm-create-smcp.html

Comme conseillez dans la documentation, faites un namespace dedié comme par exemple `istio-system`

Créez égallement un second namespace pour le rajouter au `ServiceMeshMemberRoll` , c'est égallement le namespace où l'on déploiera notre workload faisant partie du mesh :
https://docs.openshift.com/container-platform/4.8/service_mesh/v2x/ossm-create-mesh.html#ossm-member-roll-create_ossm-create-mesh

==== Preuves à fournir 

* [*Challenge 7.1.1*] Screenshot qui montre l'installation des 4 Operators
* [*Challenge 7.1.2*] Screenshot qui les annotations du project/namespace qui a été rajouté au mesh. Des annotations spécifiques du service mesh doivent y figurer.

=== Déployer un workload, un Destination Rule et un Virtual Service dans le mesh

Maintenant que tout est installé nous pouvons déployer un service, ainsi que 2 deployments ayant des versions différentes. 

Forker ce repo : https://github.com/sebastienblanc/antennas-incident

A l'intérieur du répertoire `istio` appliquez toutes les resources qui s'y trouvent dans cet ordre : 

* IncidentDeploymentV1
* IncidentDeploymentV2
* Gateway
* DestinationRule
* VirtualService

==== Preuves à fournir

* [*Challenge 7.2.1*] Une URL qui montre que le traffic est balancé à 75% vers la v1 et 25% vers la v2beta2


Bravo ! 






